import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  email: process.env.REACT_APP_SHEETS_EMAIL,
  key: process.env.REACT_APP_SHEETS_PRIVATE_KEY!,
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});

export const getDb =async () => {
    const doc = new GoogleSpreadsheet(process.env.REACT_APP_SHEETS_ID!, serviceAccountAuth);
    await doc.loadInfo(); // loads document properties and worksheets

    return doc;
}