import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  email: process.env.REACT_APP_SHEETS_EMAIL,
  key: process.env.REACT_APP_SHEETS_PRIVATE_KEY!,
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});

export const getDbDays = async () => {
    const doc = new GoogleSpreadsheet(process.env.REACT_APP_SHEETS_DAYS_ID!, serviceAccountAuth);
    await doc.loadInfo();

    return doc;
}

export const getDbStandings = async () => {
  const doc = new GoogleSpreadsheet(process.env.REACT_APP_SHEETS_STANDINGS_ID!, serviceAccountAuth);
  await doc.loadInfo();

  return doc;
}